# path to folder where DANNCE weights and logs will be saved
RESULTSDIR: ./COM/train_results/
RESULTSDIR_PREDICT: ./COM/predict_results/

# How to crop the input images. The U-Net expects each dimension size to be a multiple of 32.
CROP_HEIGHT: [0, 1024]
CROP_WIDTH: [20, 1300]

# Number of channels for each input image (e.g. RGB == 3)
N_CHANNELS_IN: 3

# Number of network output channels.
N_CHANNELS_OUT: 1

# BATCH_SIZE*len(CAMNAMES) should be <= 6 for most COM training applications
BATCH_SIZE: 2

# Number of parallel workers serving data to the model
WORKERS: 2

# Max. number of batches in multi-processing queue
MAX_QUEUE_SIZE: 10

# DANNCE training option. Sets the size of the 3D Guassians (in mm) used as labels for the MAX models
SIGMA: 10

# DANNCE training option. Sets the number of epochs during training
EPOCHS: 100

# DANNCE training option. Sets the verbosity of training output
VERBOSE: 1

# Degree of downsampling applied to image input. Default 1, other values untested.
DOWNFAC: 2

# DANNCE training option. Loss function to be used. Default MSE.
loss: mask_nan_keep_loss

# DANNCE training option. Learning rate for the Adam optimizer. Default 1e-3.
lr: 5e-5

# By default, will load in the first hdf5 file at this location for fine-tuning. If training from scratch, set to None
weights: ./COM/weights/

# During prediction, will look for the last epoch weights saved to ./COM/train_results/. To load in a different weights file, add the path here
#predict_weights: path_to_weights_file

# name of the network architecture (see nets.py)
net: unet2d_fullbn

# If true, each camera's video directory contains only the video files. If false, each camera's video directory contains an additional subdirectory, which then contains the video files
vid_dir_flag: False

# DANNCE training. Metric to be monitored in addition to loss
metric: mse

# Set the video extension
extension: .mp4

# How many samples from each animal do you want to (randomly) set aside for a validation metric?
num_validation_per_exp: 5

# If true, saves plots of the training labels overlaid on images
debug: True

# Path to load in a specific set of validation sampleIDs
#load_valid: 

# Path to a list of experiment config files. By Default, train_COMfinder.py will look for exp*.yaml files in the same directory as this file
#exp_path: [exp1.yaml, exp2.yaml, exp3.yaml]

# When using a system with multiple GPUs, we should just target one ofthem
gpuID: "0"

# Number of frames in each video file
chunks: 3500

# If present, write the confidence map output and image/COM overlays to disk during prediction
#COMdebug: CameraLmouse

# How many frames to you want to predict over? Set to 'max' for all video frames.
max_num_samples: 40000

# For prediction, False means Matlab will do the undistort, True means python will do it (slower)
undistort: False